baseURL = "https://cloudforet-io.github.io/v1-12"
languageCode = "en-us"
title = "Cloudforet"
theme = "docsy"

# robots.txt
enableRobotsTXT = true

# google analytics
googleAnalytics = "G-VGD2HRSKL3"

# sitemap
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

# Will give values to .Lastmod etc.
enableGitInfo = true

# Enable Emoji emoticons support for page content
# See https://www.webfx.com/tools/emoji-cheat-sheet/
enableEmoji = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

disableKinds = ["taxonomy", "taxonomyTerm"]
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
pygmentsStyle = "tango"

[languages]
[languages.en]
    languageName ="English"
    title = "Cloudforet | Open Source Multi-cloud Management Platform"
    contentDir = "content/en"
    time_format_default = "02.01.2006"
		time_format_blog = "02.01.2006"
    # Weight used for sorting.
    weight = 1
    description = "Manage multi-cloud environments and your all cloud resources & cost in a single platform that offers support for AWS, Azure, Google Cloud, and more."

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
section = [ "HTML", "print" ]

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true
extensions = [
  "laxHtmlBlocks",
  "hardLineBreak", # newlines result in line breaks
]

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Options to using html inline markdown
[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark]
[markup.goldmark.extensions]
    footnote = true
    definitionList = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = false
[markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4

[markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[params]
version_menu = "Versions"
copyright = "Cloudforet Foundation"
#privacy_policy = "https://policies.google.com/privacy"
latest = "v1.12"
#archived_version = true
# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/cloudforet-io/cloudforet-io.github.io"
body_classes = "georgia bg-near-white"
# Enable Algolia DocSearch
algolia_docsearch = false
# Enable Lunr.js offline search
offlineSearch = true
showedit = true
docsbranch = "master"
currentUrl = "https://cloudforet-io.github.io/home/"
# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false
# Configure url of latest version
# url_latest_version = ""
subtitle = "Cloudforet"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_cache_limit = 10
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

[[params.versions]]
fullversion = "v1.12"
version = "v1.12 (stable)"
githubbranch = "release-1.12.0"
docsbranch = "master"
# Set master version url
url = "/"

fullversion = "latest"
version = "latest"
githubbranch = "master"
docsbranch = "master"
# Set master version url
url = "https://cloudforet-io.github.io"

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

[[menu.main]]
    identifier = "community"
    name = "Community"
    url = "/community/"
    weight = 4

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5

[[menu.footer]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.footer]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

[[menu.footer]]
    identifier = "community"
    name = "Community"
    url = "/community/"
    weight = 4

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5

[[menu.footer]]
    identifier = "privacy"
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 6

[[menu.footer]]
    identifier = "terms"
    name = "Terms of Service"
    url = "/terms/"
    weight = 7

[[menu.footer]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 8

[[menu.footer]]
    identifier = "github"
    name = "GitHub"
    url = "
